# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a1:
    has_velocity_limits: true
    max_velocity: 2.687807048071268
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a2:
    has_velocity_limits: true
    max_velocity: 2.687807048071268
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a3:
    has_velocity_limits: true
    max_velocity: 3.979350694547072
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a4:
    has_velocity_limits: true
    max_velocity: 5.98647933434055
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a5:
    has_velocity_limits: true
    max_velocity: 6.702064327658226
    has_acceleration_limits: false
    max_acceleration: 0
  joint_a6:
    has_velocity_limits: true
    max_velocity: 12.58382390687912
    has_acceleration_limits: false
    max_acceleration: 0
  left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0